[package]
name = "old_rusty_platforms"
version = "0.1.0"
edition = "2021"
authors = ["Aleksandr Kovalev <aleksandr@kovalev.engineer>"]

[dependencies]
pixels = "0.13.0"
rand = "0.8.5"
winit = "0.28.6"
winit_input_helper = "0.14.1"
